steps:
  - name: 'node'
    entrypoint: 'yarn'
    args: ['install']
  
  - name: 'node'
    entrypoint: 'yarn'
    args: ['run', 'build']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']
    args:
      - app
      - deploy
      - app.yaml
      - --set-env-vars=REACT_APP_API_URL=${_REACT_APP_API_URL}
      